[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
    fastled/FastLED
    mathieucarbou/ESPAsyncWebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson
